[rospy.client][INFO] 2022-01-06 17:48:02,771: init_node, name[/display_map], pid[8508]
[xmlrpc][INFO] 2022-01-06 17:48:02,772: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-01-06 17:48:02,772: Started XML-RPC server [http://prajwal-IdeaPad-L340-15IRH-Gaming:41651/]
[rospy.init][INFO] 2022-01-06 17:48:02,772: ROS Slave URI: [http://prajwal-IdeaPad-L340-15IRH-Gaming:41651/]
[rospy.impl.masterslave][INFO] 2022-01-06 17:48:02,772: _ready: http://prajwal-IdeaPad-L340-15IRH-Gaming:41651/
[rospy.registration][INFO] 2022-01-06 17:48:02,773: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-01-06 17:48:02,773: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-01-06 17:48:02,872: registered with master
[rospy.rosout][INFO] 2022-01-06 17:48:02,873: initializing /rosout core topic
[rospy.rosout][INFO] 2022-01-06 17:48:02,882: connected to core topic /rosout
[rospy.simtime][INFO] 2022-01-06 17:48:02,883: initializing /clock core topic
[rospy.simtime][INFO] 2022-01-06 17:48:02,886: connected to core topic /clock
[rospy.internal][INFO] 2022-01-06 17:48:02,888: topic[/clock] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:39525/], count 0
[rospy.internal][INFO] 2022-01-06 17:48:03,098: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-01-06 17:48:03,701: topic[/grid3/mat] adding connection to [/rviz], count 0
[rospy.internal][ERROR] 2022-01-06 17:55:57,819: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:52385 (http://prajwal-IdeaPad-L340-15IRH-Gaming:39525/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 52385 to [127.0.0.1:44684 on socket 18]] [/display_map].

[rospy.core][INFO] 2022-01-06 17:55:58,147: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-01-06 17:55:58,151: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-01-06 17:55:58,151: topic[/grid3/mat] removing connection to /rviz
[rospy.internal][INFO] 2022-01-06 17:55:58,151: topic[/clock] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:39525/
[rospy.impl.masterslave][INFO] 2022-01-06 17:55:58,151: signal-2
[rospy.core][INFO] 2022-01-06 17:56:00,193: signal_shutdown [atexit]
